[package]
name = "rust-payments-engine"
version = "0.1.0"
authors = ["Mikael Lindlof <mikael@lindlof.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
anyhow = { version = "1.0" }
thiserror = "1.0.23"
